config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end
  root 'items#index'
end

app/models/convert_table.rb
class ConvertTable < ActiveRecord::Base; end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :priority

  def completed?
    !completed_at.blank?
  end
end

app/models/priority.rb
class Priority < ActiveRecord::Base; end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base; end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_action :show_item, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
    @items = Item.where(:user_id => current_user.id).order("completed_at").order("priority_id DESC")
    end
  end

  def new
    @item = current_user.items.build
  end

  def show
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private
    def item_params
      params.require(:item).permit(:title, :description, :priority_id)
    end

    def show_item
      @item = Item.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/priority_helper.rb
module PriorityHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: 'Item' %>
    <%= f.input :description %>
    <h5><b>Priority:</b></h5>
    <div class="col-md-2">
      <div class="row">
      <%= f.collection_radio_buttons :priority_id, [[1, 'Low']  ,[2, 'Middle'], [3, 'High']], :first, :last, checked: 2 %>
      </div>
    </div>
    <%= f.button :submit %>
<% end %>

app/views/items/_item.html.erb
<div style="border-bottom-color: <%=  item.priority.color %>;"
  <% if item.completed? %> class="row item" <% else %>
  <% if item.priority.priority_level == 3 %> class="row item alert alert-success" <% end %>
  <% if item.priority.priority_level == 2 %> class="row item alert alert-warning" <% end %>
  <% if item.priority.priority_level == 1 %> class="row item alert alert-danger" <% end %>
  <% end %>
>
  <div class="col-md-8">
    <h2 style="<%= 'opacity: 0.2;' if item.completed? %>" class="item-title" ><%= item.completed? ? sanitize("<del>#{ link_to(item.title, item) }</del>") : link_to(item.title, item)  %></h2>
    <p style="<%= 'opacity: 0.2;' if item.completed? %>" class="item-desc item-sub-title"><%= item.description %></p>
    <br><p style="opacity: 0.2;" class="time-ago"><%= item.completed? ? "Closed #{time_ago_in_words(item.completed_at)} ago" : "Created #{time_ago_in_words(item.created_at)} ago" %></p>
  </div>
  <div class="col-md-2">
    <% if item.completed? %>
      <p></p>
      <i style="opacity: 0.2;" class="fa fa-lg fa-check">Done</i>
    <% else %>
      <p><%= link_to complete_item_path(item), method: :patch do %></p>
      <i class="fa fa-lg fa-check">Done</i>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-2">
    <p><%= link_to item, method: :delete, data: { confirm: 'Delete this task?' } do %></p>
    <i class="fa fa-lg fa-trash">Delete</i>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <% if @item.completed? %>
    <h3>WAT? How you...</h3>
    <h2>Anyway, your task is CLOSED.</h2>
    <h4>Now try remove your task.</h4>
    <br>
    <p><%= link_to @item, method: :delete do %></p>
    <i class="fa fa-lg fa-trash">Delete</i>
    <% end %>
    <% else %>
      <h2>Edit TODOList </h2>
      <%= render 'form' %>
    <% end %>
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <div class="index-wrapper">
      <%= render partial: 'item', collection: @items %>
    </div>
  </div>
<% else %>
 <%= render 'layouts/static_landing_page' %>
<% end %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h2>New TODOList task</h2>
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <div style="border-bottom-color: <%=  @item.priority.color %>;"
      <% if @item.completed? %> class="row item" <% else %>
      <% if @item.priority.priority_level == 3 %> class="row item alert alert-success" <% end %>
      <% if @item.priority.priority_level == 2 %> class="row item alert alert-warning" <% end %>
      <% if @item.priority.priority_level == 1 %> class="row item alert alert-danger" <% end %>
      <% end %>
    >
      <div class="col-md-8">
        <h2 style="<%= 'opacity: 0.2;' if @item.completed? %>" class="item-title" ><%= @item.completed? ? sanitize("<del>#{ @item.title }</del>") : @item.title %></h2>
        <p style="<%= 'opacity: 0.2;' if @item.completed? %>" class="item-desc item-sub-title"><%= @item.description %></p>
        <p style="<%= 'opacity: 0.2;' if @item.completed? %>" >Priority: <%=  @item.priority.name %>
        <p style="opacity: 0.2;" class="item-desc item-sub-title"><%= @item.completed? ? "Closed #{time_ago_in_words(@item.completed_at)} ago" : "Created #{time_ago_in_words(@item.created_at)} ago" %></p>
      </div>
      <div class="col-md-2">
        <p><%= link_to root_path, method: :get do %></p>
        <i class="fa fa-lg fa-reply">Back</i>
        <% end %>
      </div>
      <div class="col-md-2">
        <% if @item.completed? %>
          <p><%= link_to @item, method: :delete, data: { confirm: 'Delete this task?' } do %></p>
          <i class="fa fa-lg fa-trash">Delete</i>
          <% end %>
        <% else %>
          <p><%= link_to edit_item_path(@item), method: :get do %></p>
          <i class="fa fa-lg fa-wrench">Edit</i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/static_landing_page' %>
<% end %>

app/views/layouts/_static_landing_page.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="jumbotron">
    <h2>Your personal TODOList.</h2>
    <h4>Create your TODOList and start plan your day!</h4>
    <br>
    <%=  link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
    or <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODOList</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'TODOList by R1cro', root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user.present? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Sign in', new_user_session_path%></li>
        <li><%= link_to 'New here?', new_user_registration_path%></li>
      <% end %>
    </ul>
    <p style="opacity: 0.3;" class="notice navbar-text navbar-center"><%= notice %></p>
    <p style="opacity: 0.3;" class="alert navbar-text navbar-center"><%= alert %></p>
    <% if user_signed_in? %>
        <%= link_to 'Create new task!', new_item_path, class: "navbar-text navbar-link navbar-right" %>
    <% end %>
  </div>
</nav>

<div class="container">
    <%= yield %>
</div>

</body>
</html>